### ISSUE TITLE
GUI for Geyser Players

### ISSUE THREAD

**Issue by RealTriassic** [RoinujNosde/SimpleClans#330]
**Is your feature request related to a problem? Please describe.**
Currently, if you want to keep the inventory GUI enabled for the plugin, Bedrock Players have to use the clunky inventory GUI too, this is a big experience downgrade for bedrock edition players as they either have to stick with the clunky GUI or type out commands themselves.

**Describe the solution you'd like**
Use the Floodgate API to add special GUIs for Bedrock Players by using Bedrock's special forms feature, this would solve the issue of Bedrock Players having to use the inventory GUI system by instead giving them forms.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by RoinujNosde** [comment]
Awesome suggestion! :)

If you would like to help speed up the process, write "how" each command (or feature) can be translated into a form.

Example:
/clan create -> CustomForm, title "Create a clan", 2 inputs for the tag and name.
Confirmation frame -> ModalForm, button "Confirm", button "Cancel"

**Comment by Tazler89** [comment]
personally i would not recommend this, the bedrock forms is horrid, its big and bold with very little space, you can also not include over lore, commands for the forms is not going to be as advanced, and takes up the complete screen, as someone who has for many years used both bedrock and java and have kids playing consoles, the inv GUI is much better, more space and hover details with lore space to give great detail, from the time i have spent on it there is 100% no advantage to using forms over inv GUI for bedrock.

**Comment by RealTriassic** [comment]
The inventory GUI is horrid when viewing on a mobile device

**Comment by Tazler89** [comment]
that maybe so but its a lot of work just to support 1 platform, the amount of devices in question to how many it would benefit, it know there are plugins that can return the device type and depending on the set device can open other types of GUI but the efforts that would need to be put into this just for them very few that not many people use, like looking at a bedrock usage % lets say 40% xbox, 40% playsation, 10% Nintendo 5% tablets and 5% phones that don't look good with the inv GUI its a lot of work to do and a hella lot of time just for 5% of users. 

This would be something as a server owner you would do to your own customer base, me personally have stripped down every plugin i have and custom made every GUI and even making GUI for plugins that don't have one covering all commands so that bedrock players only need to use a select few commands to open the GUI, this has taken months and i'm still not finished, if i had to do this all again just for the 5%... see how its just not worth it. let alone 1 plugin supporting the 5% you still have another 100 plus commands that phone users would have to use.
