### ISSUE TITLE
Restore old clan create command with args

### ISSUE THREAD

**Issue by RoinujNosde** [RoinujNosde/SimpleClans#76]

**Comment by xtomyserrax** [comment]
It would be amazing to have both alternatives. An actual problem I was testing is that if a player is muted, then this thing for creating a clan with chat kind of glitches because the player is not allowed to talk. He had to wait until the end of his mute to work with his clan (he couldnt even perform commands if I remember correctly)

**Comment by RoinujNosde** [comment]
@xtomyserrax I really need to add a timeout for those conversations.
